export const {
    APP,
    LOG,
    ERROR,
    WARN,
    DEBUG,
    VERBOSE,
    FAILED_TO_ROTATE,
    FAILED_TO_CHECK_LOG_FILE,
    NO_CONTEXT,
    FAILED_TO_WRIT_LOG_FILE,
    INCOMING_REQUEST,
    OUTGOING_RESPONSE,
    PASSWORD,
    REFRESH_TOKEN,
    TOKEN,
} = {
    APP: 'app',
    LOG: 'log',
    ERROR: 'error',
    WARN: 'warn',
    DEBUG: 'debug',
    VERBOSE: 'verbose',
    PASSWORD: 'password',
    TOKEN: 'token',
    REFRESH_TOKEN: 'refreshToken',
    FAILED_TO_ROTATE: 'Failed to rotate log file',
    FAILED_TO_CHECK_LOG_FILE: 'Failed to check log file size',
    NO_CONTEXT: '..no context..',
    FAILED_TO_WRIT_LOG_FILE: 'Failed to write log file',
    INCOMING_REQUEST: 'Incoming request',
    OUTGOING_RESPONSE: 'Outgoing response',
} as const;